name: Build

on: push

jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -o gw2-addon-setup-debug.exe

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: gw2-addon-setup-debug
          path: gw2-addon-setup-debug.exe

  sign-and-release:
    name: Sign and Release
    runs-on: windows-2022
    needs: build
    environment: release
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: gw2-addon-setup-debug

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Sign files with Trusted Signing
        uses: azure/trusted-signing-action@v0.5.0
        with:
          endpoint: https://weu.codesigning.azure.net/
          trusted-signing-account-name: jsc-trustedsigning
          certificate-profile-name: public-trust
          files: ${{ github.workspace }}\gw2-addon-setup-debug.exe
          file-digest: SHA256
          timestamp-rfc3161: http://timestamp.acs.microsoft.com
          timestamp-digest: SHA256
          exclude-environment-credential: true
          exclude-workload-identity-credential: true
          exclude-managed-identity-credential: true
          exclude-shared-token-cache-credential: true
          exclude-visual-studio-credential: true
          exclude-visual-studio-code-credential: true
          exclude-azure-cli-credential: false
          exclude-azure-powershell-credential: true
          exclude-azure-developer-cli-credential: true
          exclude-interactive-browser-credential: true

      - name: Upload signed build
        uses: actions/upload-artifact@v4
        with:
          name: gw2-addon-setup-debug-signed
          path: gw2-addon-setup-debug.exe

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: gw2-addon-setup-debug.exe
